Branch test
hon-g/ichiyasaGitSample pull request #4
Opened 2020-01-05 08:24 UTC by honda202270

### 変更内容
branch操作のテスト用にコミットを2回実行

2020-01-05 08:38 UTC, honda-yahoo commented on index.html
>                  <p>このコミュニティーは、非営利目的で活動しています。</p>
この行にもコメントを追加してもらってもいいですか？

2020-01-13 02:43 UTC, hon-y requested changes
1点指摘したので、修正をお願いします。

2020-01-13 03:00 UTC, hon-g commented
修正したものをプッシュしたので、再度確認をお願いします。

2020-01-13 03:05 UTC, hon-y commented
修正ありがとうございます。

2020-01-13 03:15 UTC, merged